name: build
on: [push, pull_request]
jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: set up go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: check out code
      uses: actions/checkout@v2

    - name: install golangci-lint and goveralls
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.20.0
         GO111MODULE=off go get -u github.com/mattn/goveralls

    - name: test and lint
      run: |
        go test -mod=vendor -covermode=count -coverprofile=profile.cov ./...
        $GITHUB_WORKSPACE/golangci-lint run

    - name: submit coverage
      run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: build docker image
      run: docker build .


